// textures/ barrel — importing this file registers every texture primitive.
// Primitive list mirrors shaders.com/docs/components Textures section.

export { default as Aurora } from './aurora'
export { default as Beam } from './beam'
export { default as Blob } from './blob'
export { default as Checkerboard } from './checkerboard'
export { default as DomTexture } from './domtexture'
export { default as DotGrid } from './dot-grid'
export { default as FallingLines } from './falling-lines'
export { default as FloatingParticles } from './floating-particles'
export { default as FlowingGradient } from './flowing-gradient'
export { default as Gradient } from './gradient'
export { default as GodRays } from './godrays'
export { default as Grid } from './grid'
export { default as HexGrid } from './hex-grid'
export { default as ImageTexture } from './image-texture'
export { default as MultiPointGradient } from './multi-point-gradient'
export { default as Plasma } from './plasma'
export { default as Ripples } from './ripples'
export { default as SimplexNoise } from './simplex-noise'
export { default as SineWave } from './sine-wave'
export { default as SolidColor } from './solid-color'
export { default as Spiral } from './spiral'
export { default as Strands } from './strands'
export { default as Stripes } from './stripes'
export { default as StudioBackground } from './studio-background'
export { default as Swirl } from './swirl'
export { default as Truchet } from './truchet'
export { default as VideoTexture } from './video-texture'
export { default as Voronoi } from './voronoi'
export { default as Weave } from './weave'
export { default as WebcamTexture } from './webcam-texture'
