// Emits a small React component that imports the shared `shader-mount`
// runtime and calls it with this shader's bundle. Each export is just the
// shader-specific bits (fragment passes, vertex, uniform metadata, defaults
// + a typed Props interface); all WebGL plumbing lives in the single
// shipped `shader-mount.ts`.
//
// The output assumes the consumer has installed `shader-mount.ts` alongside
// (the shadcn-style registry takes care of this — see Phase 4 in the plan).

import type { GeneratedPass, GeneratedUniform } from '../types'
import { computePropNames } from './typescript'
import { exportable } from './vanilla'

export function generateReactComponent(
  uniforms: GeneratedUniform[],
  shaderName: string,
  passes: GeneratedPass[],
  vertexShader: string,
): string {
  const props = exportable(uniforms)
  const propNames = computePropNames(props)
  const passEntries = passes
    .map(
      (p) =>
        `  { fragment: ${JSON.stringify(p.fragmentShader)}, readsPrevPass: ${p.readsPrevPass} }`,
    )
    .join(',\n')

  const uniformSpecs = props
    .map((u) => {
      const arr = u.arrayLength !== undefined ? `, arrayLength: ${u.arrayLength}` : ''
      return `  { name: ${JSON.stringify(u.name)}, type: ${JSON.stringify(u.type)}, default: ${defaultLiteral(u)}${arr} }`
    })
    .join(',\n')

  const propsType = props
    .map((u) => `  ${propNames.get(u.name)}?: ${tsType(u)}`)
    .join('\n')

  const propMappings = props
    .map(
      (u) =>
        `      ${JSON.stringify(u.name)}: p.${propNames.get(u.name)} ?? DEFAULTS[${JSON.stringify(u.name)}]`,
    )
    .join(',\n')

  return `// Auto-generated by shader-composer. Do not edit by hand.
import { useEffect, useRef } from 'react'
import { mountShader, type UniformSpec } from './shader-mount'

const VERTEX_SHADER = ${JSON.stringify(vertexShader)}

const PASSES = [
${passEntries}
]

const UNIFORMS: UniformSpec[] = [
${uniformSpecs}
]

const DEFAULTS: Record<string, unknown> = Object.fromEntries(
  UNIFORMS.map((u) => [u.name, u.default]),
)

export interface ${shaderName}Props {
${propsType}
  pixelRatio?: number
  className?: string
  style?: React.CSSProperties
}

export function ${shaderName}(props: ${shaderName}Props): React.ReactElement {
  const ref = useRef<HTMLCanvasElement | null>(null)
  const propsRef = useRef(props)
  propsRef.current = props

  useEffect(() => {
    const canvas = ref.current
    if (!canvas) return

    function valuesFromProps(p: ${shaderName}Props): Record<string, unknown> {
      return {
${propMappings}
      }
    }

    const handle = mountShader(canvas, {
      vertex: VERTEX_SHADER,
      passes: PASSES,
      uniforms: UNIFORMS,
      values: valuesFromProps(propsRef.current),
      pixelRatio: propsRef.current.pixelRatio,
    })

    let frame = 0
    const tick = () => {
      handle.update(valuesFromProps(propsRef.current))
      frame = requestAnimationFrame(tick)
    }
    frame = requestAnimationFrame(tick)

    return () => {
      cancelAnimationFrame(frame)
      handle.destroy()
    }
  }, [])

  return (
    <canvas
      ref={ref}
      className={props.className}
      style={{ display: 'block', width: '100%', height: '100%', ...props.style }}
    />
  )
}
`
}

function tsType(u: GeneratedUniform): string {
  switch (u.type) {
    case 'float':
    case 'int':
      return 'number'
    case 'bool':
      return 'boolean'
    case 'vec2':
      return '[number, number]'
    case 'vec3':
      return '[number, number, number]'
    case 'vec4':
      return '[number, number, number, number]'
    case 'sampler2D':
      return 'string | { url?: string | null; fit?: "cover" | "contain" | "fill"; scale?: number; rotation?: number; offsetX?: number; offsetY?: number } | null'
    case 'vec4Array':
      return 'number[][]'
  }
}

function defaultLiteral(u: GeneratedUniform): string {
  const v = u.default
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return JSON.stringify(v)
  if (typeof v === 'object') {
    if ('values' in (v as Record<string, unknown>)) {
      return JSON.stringify((v as { values: number[][] }).values)
    }
    return JSON.stringify(v)
  }
  return JSON.stringify(v)
}
