// Emits a self-contained React component that renders the generated shader.
// Inlines runtime-shell + image-helper sources verbatim so the export has no
// external dependencies beyond React itself.

import runtimeShellSource from '../runtime/runtime-shell.ts?raw'
import imageHelperSource from '../runtime/export-image-helper.ts?raw'
import type { GeneratedPass, GeneratedUniform } from '../types'
import { computePropNames, exportable } from './typescript'

const INLINED_RUNTIME = runtimeShellSource.replace(/^export /gm, '')
const INLINED_IMAGE_HELPER = imageHelperSource.replace(/^export /gm, '')

export function generateReactComponent(
  uniforms: GeneratedUniform[],
  shaderName: string,
  passes: GeneratedPass[],
  vertexShader: string,
): string {
  const props = exportable(uniforms)
  const propNames = computePropNames(props)
  const passSources = passes
    .map(
      (p) =>
        `  { fragment: ${JSON.stringify(p.fragmentShader)}, readsPrevPass: ${p.readsPrevPass}, mode: ${JSON.stringify(p.mode ?? null)} }`,
    )
    .join(',\n')

  const bindings = props.map((u) => bindUniform(u, propNames)).join('\n')

  return `// Auto-generated by shader-composer. Do not edit by hand.
import { useEffect, useRef } from 'react'

${INLINED_IMAGE_HELPER}

${INLINED_RUNTIME}

${defaultsBlock(props, propNames)}

export interface ${shaderName}Props {
${props.map((u) => `  ${propNames.get(u.name)}?: ${tsType(u)}`).join('\n')}
  pixelRatio?: number
  startTime?: number
  className?: string
  style?: React.CSSProperties
}

const VERTEX_SHADER = ${JSON.stringify(vertexShader)}

const PASSES = [
${passSources}
]

export function ${shaderName}(props: ${shaderName}Props): React.ReactElement {
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const propsRef = useRef(props)
  propsRef.current = props

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const gl = canvas.getContext('webgl2', { premultipliedAlpha: false })
    if (!gl) {
      console.error('WebGL2 not supported')
      return
    }

    const cache = createImageCache(gl)
    const pipeline = createShaderPipeline(gl, VERTEX_SHADER, PASSES)
    const startTime = (propsRef.current.startTime ?? 0) * 1000 - performance.now()
    let frame = 0

    function ensureSize() {
      const ratio = propsRef.current.pixelRatio ?? window.devicePixelRatio ?? 1
      const rect = canvas!.getBoundingClientRect()
      const w = Math.max(1, Math.round(rect.width * ratio))
      const h = Math.max(1, Math.round(rect.height * ratio))
      if (canvas!.width !== w || canvas!.height !== h) {
        canvas!.width = w
        canvas!.height = h
      }
      return { w, h }
    }

    function tick() {
      const p = propsRef.current
${ensureCalls(props, propNames)}
      const { w, h } = ensureSize()
      const time = (performance.now() + startTime) / 1000
      pipeline.render(time, w, h, (ctx, prog) => {
        let unit = ctx.nextTextureUnit
${bindings}
      })
      frame = requestAnimationFrame(tick)
    }
    tick()

    return () => {
      cancelAnimationFrame(frame)
      pipeline.destroy()
      cache.destroy()
    }
  }, [])

  return (
    <canvas
      ref={canvasRef}
      className={props.className}
      style={{ display: 'block', width: '100%', height: '100%', ...props.style }}
    />
  )
}
`
}

function tsType(u: GeneratedUniform): string {
  switch (u.type) {
    case 'float':
    case 'int':
      return 'number'
    case 'bool':
      return 'boolean'
    case 'vec2':
      return '[number, number]'
    case 'vec3':
      return '[number, number, number]'
    case 'vec4':
      return '[number, number, number, number]'
    case 'sampler2D':
      return 'ImageProp'
    case 'vec4Array':
      return 'number[][]'
  }
}

function defaultLiteral(u: GeneratedUniform): string {
  const v = u.default
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return JSON.stringify(v)
  if (typeof v === 'object') {
    if ('values' in (v as Record<string, unknown>)) {
      return JSON.stringify((v as { values: number[][] }).values)
    }
    if ('url' in (v as Record<string, unknown>)) {
      return JSON.stringify(v)
    }
  }
  return JSON.stringify(v)
}

function defaultsBlock(
  props: GeneratedUniform[],
  names: Map<string, string>,
): string {
  const entries = props
    .map((u) => `  ${names.get(u.name)}: ${defaultLiteral(u)}`)
    .join(',\n')
  return `const DEFAULTS = {\n${entries},\n}`
}

function ensureCalls(
  props: GeneratedUniform[],
  names: Map<string, string>,
): string {
  const lines: string[] = []
  for (const u of props) {
    if (u.type !== 'sampler2D') continue
    const prop = names.get(u.name)!
    lines.push(
      `      cache.ensure(p.${prop} ?? (DEFAULTS as any).${prop})`,
    )
  }
  return lines.join('\n')
}

function bindUniform(u: GeneratedUniform, names: Map<string, string>): string {
  const prop = names.get(u.name)!
  const fallback = `(DEFAULTS as any).${prop}`
  switch (u.type) {
    case 'float':
    case 'int':
      return `        { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) gl.uniform1f(loc, p.${prop} ?? ${fallback}) }`
    case 'bool':
      return `        { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) gl.uniform1i(loc, (p.${prop} ?? ${fallback}) ? 1 : 0) }`
    case 'vec2':
      return `        { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = p.${prop} ?? ${fallback}; gl.uniform2f(loc, v[0], v[1]) } }`
    case 'vec3':
      return `        { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = p.${prop} ?? ${fallback}; gl.uniform3f(loc, v[0], v[1], v[2]) } }`
    case 'vec4':
      return `        { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = p.${prop} ?? ${fallback}; gl.uniform4f(loc, v[0], v[1], v[2], v[3]) } }`
    case 'sampler2D':
      return `        unit = bindSamplerUniform(gl, prog, ${JSON.stringify(u.name)}, p.${prop} ?? ${fallback}, cache, unit)`
    case 'vec4Array':
      return `        bindPaletteUniform(gl, prog, ${JSON.stringify(u.name)}, p.${prop} ?? ${fallback}, ${u.arrayLength ?? 10})`
  }
}

