// Emits a self-contained vanilla-JS function that mounts the generated shader
// onto a canvas element. Same source-of-truth as the React export — the
// runtime-shell + image-helper sources are inlined verbatim.

import runtimeShellSource from '../runtime/runtime-shell.ts?raw'
import imageHelperSource from '../runtime/export-image-helper.ts?raw'
import type { GeneratedPass, GeneratedUniform } from '../types'
import { computePropNames, exportable } from './typescript'

const INLINED_RUNTIME = runtimeShellSource.replace(/^export /gm, '')
const INLINED_IMAGE_HELPER = imageHelperSource.replace(/^export /gm, '')

export function generateVanillaJs(
  uniforms: GeneratedUniform[],
  shaderName: string,
  passes: GeneratedPass[],
  vertexShader: string,
): string {
  const props = exportable(uniforms)
  const propNames = computePropNames(props)
  const passSources = passes
    .map(
      (p) =>
        `  { fragment: ${JSON.stringify(p.fragmentShader)}, readsPrevPass: ${p.readsPrevPass}, mode: ${JSON.stringify(p.mode ?? null)} }`,
    )
    .join(',\n')

  const bindings = props.map((u) => bindUniform(u, propNames)).join('\n')
  const ensures = props
    .filter((u) => u.type === 'sampler2D')
    .map((u) => {
      const n = propNames.get(u.name)!
      return `      cache.ensure(props.${n} ?? DEFAULTS.${n})`
    })
    .join('\n')

  const defaults = props
    .map((u) => `  ${propNames.get(u.name)}: ${defaultLiteral(u)}`)
    .join(',\n')

  return `// Auto-generated by shader-composer. Do not edit by hand.

${INLINED_IMAGE_HELPER}

${INLINED_RUNTIME}

const DEFAULTS = {
${defaults},
}

const VERTEX_SHADER = ${JSON.stringify(vertexShader)}

const PASSES = [
${passSources}
]

/**
 * Mount the ${shaderName} shader onto a canvas. Returns a handle with
 * \`update(props)\` to change parameters and \`destroy()\` to tear down.
 */
export function ${shaderName}(canvas, initialProps = {}) {
  const gl = canvas.getContext('webgl2', { premultipliedAlpha: false })
  if (!gl) throw new Error('WebGL2 not supported')

  let props = { ...initialProps }
  const cache = createImageCache(gl)
  const pipeline = createShaderPipeline(gl, VERTEX_SHADER, PASSES)
  const startTime = ((props.startTime ?? 0) * 1000) - performance.now()
  let frameHandle = 0
  let stopped = false

  function ensureSize() {
    const ratio = props.pixelRatio ?? (typeof window !== 'undefined' ? window.devicePixelRatio || 1 : 1)
    const rect = canvas.getBoundingClientRect()
    const w = Math.max(1, Math.round(rect.width * ratio))
    const h = Math.max(1, Math.round(rect.height * ratio))
    if (canvas.width !== w || canvas.height !== h) {
      canvas.width = w
      canvas.height = h
    }
    return { w, h }
  }

  function tick() {
    if (stopped) return
${ensures}
    const { w, h } = ensureSize()
    const time = (performance.now() + startTime) / 1000
    pipeline.render(time, w, h, (ctx, prog) => {
      let unit = ctx.nextTextureUnit
${bindings}
    })
    frameHandle = requestAnimationFrame(tick)
  }
  tick()

  return {
    update(next) {
      props = { ...props, ...next }
    },
    destroy() {
      stopped = true
      cancelAnimationFrame(frameHandle)
      pipeline.destroy()
      cache.destroy()
    },
  }
}
`
}

function defaultLiteral(u: GeneratedUniform): string {
  const v = u.default
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return JSON.stringify(v)
  if (typeof v === 'object' && v !== null) {
    const obj = v as Record<string, unknown>
    if ('values' in obj) return JSON.stringify(obj.values)
    return JSON.stringify(v)
  }
  return JSON.stringify(v)
}

function bindUniform(u: GeneratedUniform, names: Map<string, string>): string {
  const prop = names.get(u.name)!
  const fallback = `DEFAULTS.${prop}`
  switch (u.type) {
    case 'float':
    case 'int':
      return `      { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) gl.uniform1f(loc, props.${prop} ?? ${fallback}) }`
    case 'bool':
      return `      { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) gl.uniform1i(loc, (props.${prop} ?? ${fallback}) ? 1 : 0) }`
    case 'vec2':
      return `      { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = props.${prop} ?? ${fallback}; gl.uniform2f(loc, v[0], v[1]) } }`
    case 'vec3':
      return `      { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = props.${prop} ?? ${fallback}; gl.uniform3f(loc, v[0], v[1], v[2]) } }`
    case 'vec4':
      return `      { const loc = gl.getUniformLocation(prog, ${JSON.stringify(u.name)}); if (loc !== null) { const v = props.${prop} ?? ${fallback}; gl.uniform4f(loc, v[0], v[1], v[2], v[3]) } }`
    case 'sampler2D':
      return `      unit = bindSamplerUniform(gl, prog, ${JSON.stringify(u.name)}, props.${prop} ?? ${fallback}, cache, unit)`
    case 'vec4Array':
      return `      bindPaletteUniform(gl, prog, ${JSON.stringify(u.name)}, props.${prop} ?? ${fallback}, ${u.arrayLength ?? 10})`
  }
}
