// Emits a small vanilla-JS module that imports the shared `shader-mount`
// runtime and calls it with this shader's bundle. Each export is just the
// shader-specific bits (fragment passes, vertex, uniform metadata, defaults);
// all WebGL plumbing lives in the single shipped `shader-mount.ts`.
//
// The output assumes the consumer has installed `shader-mount.ts` alongside
// (the shadcn-style registry takes care of this — see Phase 4 in the plan).

import type { GeneratedPass, GeneratedUniform } from '../types'
import { computePropNames } from './typescript'

export function generateVanillaJs(
  uniforms: GeneratedUniform[],
  shaderName: string,
  passes: GeneratedPass[],
  vertexShader: string,
): string {
  const props = exportable(uniforms)
  const propNames = computePropNames(props)
  const passEntries = passes
    .map(
      (p) =>
        `  { fragment: ${JSON.stringify(p.fragmentShader)}, readsPrevPass: ${p.readsPrevPass} }`,
    )
    .join(',\n')

  const uniformSpecs = props
    .map((u) => {
      const arr = u.arrayLength !== undefined ? `, arrayLength: ${u.arrayLength}` : ''
      return `  { name: ${JSON.stringify(u.name)}, type: ${JSON.stringify(u.type)}, default: ${defaultLiteral(u)}${arr} }`
    })
    .join(',\n')

  const propMappings = props
    .map(
      (u) =>
        `      ${JSON.stringify(u.name)}: props.${propNames.get(u.name)} ?? props_._defaults[${JSON.stringify(u.name)}]`,
    )
    .join(',\n')

  return `// Auto-generated by shader-composer. Do not edit by hand.
import { mountShader } from './shader-mount'

const VERTEX_SHADER = ${JSON.stringify(vertexShader)}

const PASSES = [
${passEntries}
]

const UNIFORMS = [
${uniformSpecs}
]

const DEFAULTS = Object.fromEntries(UNIFORMS.map((u) => [u.name, u.default]))

/**
 * Mount the ${shaderName} shader onto a canvas. Returns a handle with
 * \`update(props)\` to push new values and \`destroy()\` to tear down.
 */
export function ${shaderName}(canvas, initialProps = {}) {
  const props_ = { _defaults: DEFAULTS }
  let props = { ...initialProps }

  function valuesFromProps(p) {
    return {
${propMappings}
    }
  }

  const handle = mountShader(canvas, {
    vertex: VERTEX_SHADER,
    passes: PASSES,
    uniforms: UNIFORMS,
    values: valuesFromProps(props),
    pixelRatio: props.pixelRatio,
  })

  return {
    update(next) {
      props = { ...props, ...next }
      handle.update(valuesFromProps(props))
    },
    destroy() {
      handle.destroy()
    },
  }
}
`
}

/**
 * Strip uniforms that the runtime owns. The mount binds these intrinsically
 * (time, resolution, mouse, layer textures, scene background, layer opacities)
 * via setSceneBackground/setLayerOpacities and the per-pass closures, so they
 * must not appear in the user-facing UNIFORMS array.
 */
export function exportable(uniforms: GeneratedUniform[]): GeneratedUniform[] {
  return uniforms.filter((u) => {
    if (u.name === 'u_time' || u.name === 'u_resolution') return false
    if (u.name === 'u_mouse' || u.name === 'u_mouseDelta') return false
    if (u.name === 'u_sceneBackground') return false
    if (u.name === 'u_noiseTexture' || u.name === 'u_prevPass' || u.name === 'u_prevFrame') return false
    if (/^u_layer_\d+(_opacity)?$/.test(u.name)) return false
    if (u.name.endsWith('_jsOutput')) return false
    return true
  })
}

function defaultLiteral(u: GeneratedUniform): string {
  const v = u.default
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) return JSON.stringify(v)
  if (typeof v === 'object') {
    if ('values' in (v as Record<string, unknown>)) {
      return JSON.stringify((v as { values: number[][] }).values)
    }
    return JSON.stringify(v)
  }
  return JSON.stringify(v)
}
